### ISSUE TITLE
Pipes breaking glitch

### ISSUE THREAD

**Issue by ryuben** [AlexTheGre4t/MCTNGIssues#11]
if i break a pipe with a tinkers tool i.e. pickaxe it will break but then reappear 
breaking with hands or anything else doesn't cause this

**Comment by AlexTheGre4t** [comment]
Are you sure this isn't just server lag? That can sometimes happen

**Comment by ryuben** [comment]
happens 100% of the time if i try to break a pipe with my tinkers pickaxe

**Comment by AlexTheGre4t** [comment]
Does the tinkers pickaxe break it instantly?

**Comment by ryuben** [comment]
pretty much - then i can break a block behind it - pipe will come back then i can break it with the pick

**Comment by ryuben** [comment]
this fixed?

**Comment by AlexTheGre4t** [comment]
After doing a little testing. It seems its just a generic minecraft issue that's been round forever. I doubt much can be done.

**Comment by Xariyl** [comment]
Might be a problem specific to the TiC tools? I remember a while back, a few other mods had issues when their blocks were broken with non-vanilla tools.

Ryuben, you have a BCA multitool? Do you have any issues breaking pipes with that?
