### ISSUE TITLE
Inscriber

### ISSUE THREAD

**Issue by ryuben** [AlexTheGre4t/MCTNGIssues#13]
This block crashes the server.....

**Comment by AlexTheGre4t** [comment]
It should be disabled. Looks like i forgot to remove the recipe. Just don't use it, all inscriber recipes have been changed to something else.

**Comment by ryuben** [comment]
yeah..about that

server is down....Some one built an inscriber and as soon as he placed it in the world the server died...and is staying dead
( i know it was this block as i was the only person online)
