### ISSUE TITLE
ME drive

### ISSUE THREAD

**Issue by ryuben** [AlexTheGre4t/MCTNGIssues#15]
it is disabled?

**Comment by AlexTheGre4t** [comment]
Yes. Only the ME chest can be used for storage

**Comment by ryuben** [comment]
Why?

**Comment by AlexTheGre4t** [comment]
The drive is very OP in terms of the technology in the pack. So is rather not encourage massive ME systems. Maybe just for small things.

**Comment by ryuben** [comment]
Ok
