### ISSUE TITLE
mod update notifications

### ISSUE THREAD

**Issue by AEnterprise** [AlexTheGre4t/MCTNGIssues#16]
i think the config options to dissable checking for mod updates should be used, only spams players with messages when logging in and serves no purpose as they shouldn't update mods on there own

**Comment by ryuben** [comment]
i said this!

**Comment by AlexTheGre4t** [comment]
Yeah. Ill do this later. Its a small thing that isn't that important compared to things in working on, so I might forget :P

**Comment by ryuben** [comment]
its called a quality of life change and its important to the person playing the pack....

**Comment by AlexTheGre4t** [comment]
I meant in the grand scheme of things this is a pretty small tweak and ill forget about it easily :P

**Comment by AlexTheGre4t** [comment]
fixed
