### ISSUE TITLE
Optifine 

### ISSUE THREAD

**Issue by ryuben** [AlexTheGre4t/MCTNGIssues#17]
Ultra - standard or light do not work with this mod pack

OptiFine_1.7.10_HD_U_B5 Crashes 
OptiFine_1.7.10_HD_B5 Crashes 
OptiFine_1.7.10_L_A4 Doesn't render pipes (looks kinda cool fluid and power just floating in mid air)

**Comment by AlexTheGre4t** [comment]
(copy from forums) 

OptiFine is a big no-no, with anything at that. Do not use it, it's not supported, buggy and i offer no assistance when it's being used. FastCraft is enabled, so that should improve FPS for you.
