### ISSUE TITLE
Lanterns and/or torches

### ISSUE THREAD

**Issue by ryuben** [AlexTheGre4t/MCTNGIssues#18]
If you add back the darkness mod, can we have a lantern and/or allow torches to give light when held in the hand? 

I had a mod a while ago that did the torch thing.

**Comment by AlexTheGre4t** [comment]
I'll have a look at a torch-style mod, i could add in dynamic lights maybe. FloodLights is going to be in build 4 at least.

**Comment by AlexTheGre4t** [comment]
i got a fix
