### ISSUE TITLE
Oil

### ISSUE THREAD

**Issue by ryuben** [AlexTheGre4t/MCTNGIssues#19]
Can we tweak oil a little so we either a get more of it or b get more of the oil desert biomes?

as atm oil is rare and with you taking out lava - for any real sustainability might turn into an issue

**Comment by AlexTheGre4t** [comment]
Will buff for next version

**Comment by ryuben** [comment]
It is going to be hard to get a balance so it might be best to try to buff the amount of oil biomes rather than the spawn rate of oil - i dunno

**Comment by AlexTheGre4t** [comment]
Im still not completely sure how extrabiomes works with BuildCraft for oil biomes and general oil spawns. But ill definitely look into some options for increased oil.

**Comment by AlexTheGre4t** [comment]
fixed
