### ISSUE TITLE
Power the Ae2 system

### ISSUE THREAD

**Issue by ryuben** [AlexTheGre4t/MCTNGIssues#21]
How do we do this - you taken out the AE2 engines and the block to convert from RF to Ae

**Comment by AlexTheGre4t** [comment]
Me controller. Its a late game thing, so id rather not have the early game option enabled. If you wanna use AE2  in the pack. You gotta be prepared for it.

**Comment by ryuben** [comment]
and the auto crafting you have taken out?

**Comment by AlexTheGre4t** [comment]
That's disabled due to me believing it replaces too much of BuildCraft's charm. AE2 has been tweaked to be a storage mod. Storage. Nothing else. Auto crafting gone, import and export busses gone, all you really need to do with it is access a terminal to get stuff out. ME interfaces do still exist though, and you use BuildCraft pipes to interact with it.

**Comment by ryuben** [comment]
we use forestry for auto crafting - buildcraft auto crafting table is so slow its almost pointless

**Comment by AlexTheGre4t** [comment]
Maybe try the laser powered auto crafting table :D

**Comment by ryuben** [comment]
only place i want auto crafting is my sorting system - could drag a pipe over to the lazer/power area but....

**Comment by Xariyl** [comment]
I use true "auto" crafting for bulk or hands-free operations, I think BC works sufficient for that. Forestry tables are good for repetitive builds -- chests, barrels, metal storage blocks, etc.

I never used AE2 auto crafting, but that ME drive was a godsend for keeping materials in one easy-to-access spot. Made manual crafting jobs real quick.

**Comment by AlexTheGre4t** [comment]
By the way. The better storage crafting station is a good auto crafter. It needs a redstone pulse for every operation but works pretty well once set up.
