### ISSUE TITLE
Elevators broken

### ISSUE THREAD

**Issue by ryuben** [AlexTheGre4t/MCTNGIssues#22]
Open blocks elevators don't work as inteded only work if u hit your head on the block can't crouch to go down either

**Comment by AlexTheGre4t** [comment]
Huh. That's a little odd. Ill have a look at that. It might just be the case of a bad OpenBlocks build as im using a development build.

**Comment by Xariyl** [comment]
Something must have happened then. They were working fine in my tower the other day, I can zip between 4 floors even with chests in the way.

**Comment by ryuben** [comment]
ima go to your tower and check it then Xariyl

they broke at yours too

**Comment by Xariyl** [comment]
Question: How much exp do you have? They take a bit of exp for each operation.

**Comment by ryuben** [comment]
0....my bad

**Comment by Xariyl** [comment]
I saw you had a drain at your base. if you're flying empty they won't work for you.

**Comment by Xariyl** [comment]
It's a config option, but I rather like to leave it on as one of the "no mob" challenges to the pack.

**Comment by AlexTheGre4t** [comment]
That's a good idea. Elevators OP must Nerf :D

**Comment by ryuben** [comment]
ok my bad they work

**Comment by Xariyl** [comment]
Lol... It's an idea. "Good" may be up to debate :)
