### ISSUE TITLE
poor ores

### ISSUE THREAD

**Issue by ryuben** [AlexTheGre4t/MCTNGIssues#23]
i got 4 stacks of gold and like 30 stacks of poor iron.....cmon that ratio is a joke

**Comment by Xariyl** [comment]
CovertJaguar actually commented one time that it was intentional. Poor iron veins can span across a dozen chunks.

**Comment by AlexTheGre4t** [comment]
Huh. Its using the default railcraft configuration for ore generation. I can only say that this is intentional.
