### ISSUE TITLE
BCA upgrades

### ISSUE THREAD

**Issue by ryuben** [AlexTheGre4t/MCTNGIssues#29]
Wiki says i can put 6 on yet i can only apply 4 :(

**Comment by AEnterprise** [comment]
you can indeed only put in 4, @AlexTheGre4t must have made a mistake when writing that wiki page

**Comment by ryuben** [comment]
IS there a way to remove upgrades atm?

**Comment by AEnterprise** [comment]
shift-left clicking on it with a machine configurator

**Comment by ryuben** [comment]
TY!

**Comment by AlexTheGre4t** [comment]
Yeah. I made the wiki page when AE was still debating the amount of upgrades that can go into a machine.

**Comment by ryuben** [comment]
I like the idea of 6 btw over power all the things
