### ISSUE TITLE
NEI Crashes

### ISSUE THREAD

**Issue by Xariyl** [AlexTheGre4t/MCTNGIssues#3]
Somewhat regularly, a client will crash when looking at a recipe in NEI with an "Internal IO Exception". Using MCTNG 3.0.0.02.

link to a crash-log sent to me by Ryuben: [ https://drive.google.com/file/d/0B1dGBeh_lXkLOUdpVWYza1Jad0U/view?usp=sharing ]

what I see in the server consol (including some other crashes he's had today): [ https://drive.google.com/file/d/0B1dGBeh_lXkLVmMyTHlTY3NvNms/view?usp=sharing ]

**Comment by AlexTheGre4t** [comment]
Thanks for this, I experienced this a lot. But only after editing Minetweaker files. So I didn't think it would be that much of a problem for the end user. But it looks like other people are experiencing this, so ill see what I can do to fix it :D

**Comment by AlexTheGre4t** [comment]
Woooo fixed
