### ISSUE TITLE
AE2 Network wrench

### ISSUE THREAD

**Issue by ryuben** [AlexTheGre4t/MCTNGIssues#39]
shift right clicking on a keb - causes the keb to pop off and disappear

**Comment by AlexTheGre4t** [comment]
This is a little odd. Can you forward this to aenterprise on the BCA repo?

**Comment by ryuben** [comment]
Could do

**Comment by AEnterprise** [comment]
hmm, this is very odd, are you sure the item didn't go in your inventory?

**Comment by ryuben** [comment]
Yep posotive - relogged might just be the pack (alex's) fault

**Comment by AEnterprise** [comment]
hmm was your inventory full at the time?

**Comment by AlexTheGre4t** [comment]
I doubt this is a modpack problem. It doesn't seem like it. Definitely a mod issue if this is a legitimate report. Ill test a little more.

**Comment by ryuben** [comment]
nope - as i said it gave the popped off action - then just went poof

dam wrong button

**Comment by AEnterprise** [comment]
explain 'popped off action' and 'poof'

**Comment by ryuben** [comment]
when you right click a KEB with a wrench it comes off the wall at full energy

Poof means disapeared as in vanished

**Comment by AEnterprise** [comment]
ok but you didn't see it in itemform for even a split second?

**Comment by ryuben** [comment]
the item seems to disappear on its way to hitting the floor

**Comment by AEnterprise** [comment]
then it's no BCA error, the only code BCA excecutes is to destroy the block and drop the item, what heapens afther that isn't BCA related, is it possible some automated thing picked it up or it did go in your inventory (backpacks or so)

**Comment by ryuben** [comment]
Just retested this - put down a Kinetic Energy Buffer

Shift right click with an AE2 network tool

Kinetic Energy Buffer just disappears 

Relogging shows the Kinetic Energy Buffer back in its place

**Comment by iTitus** [comment]
I know the cause: Somehow the PlayerInteractEvent isn't fired on the server side when using the Network Tool...

**Comment by iTitus** [comment]
AppliedEnergistics/Applied-Energistics-2#1237
